cosmo_web/bh_compute/urls.py
from django.urls import path

from . import views

app_name = 'bh_compute'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),

]

cosmo_web/cosmo_web/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bh_compute/', include('bh_compute.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cosmo_web/bh_compute/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.core.exceptions import ValidationError
import uuid


# Create your models here.
def limit():
    lim = models.Q(app_label='bh_compute', model='plane') | \
          models.Q(app_label='bh_compute', model='disk')
    return lim


class BlackHole(models.Model):
    spin = models.FloatField(default=0, verbose_name='Вращение')
    charge = models.FloatField(default=0, editable=False, verbose_name='Заряд')


class Observer(models.Model):
    distance = models.FloatField(default=100,  verbose_name='Расстояние')
    azimuthal_angle = models.FloatField(default=45,  verbose_name='Азимутальный угол')
    polar_angle = models.FloatField(default=0, blank=True, verbose_name='Полярный угол')


class Point(models.Model):
    x = models.FloatField(default=-70.711)
    y = models.FloatField(default=0)
    z = models.FloatField(default=-70.711)


class Surface(models.Model):
    surface_type = models.ForeignKey(ContentType, limit_choices_to=limit, on_delete=models.CASCADE)
    surface_id = models.PositiveIntegerField()
    surface_object = GenericForeignKey('surface_type', 'surface_id')

    class Meta:
        unique_together = ('surface_type', 'surface_id',)


class Disk(models.Model):
    ROTATING_CHOICES = (
        (True, '+'),
        (False, '-'),
    )
    direction = models.BooleanField(default=True, choices=ROTATING_CHOICES, verbose_name='Направление вращения')
    inner_radius = models.FloatField(default=6, verbose_name='Внутренний радиус')
    outer_radius = models.FloatField(default=12, verbose_name='Внешний радиус')
    surface = GenericRelation(Surface)


class Plane(models.Model):
    normal_vector_azimuthal_angle = models.FloatField(default=45, verbose_name='Нормаль к азимутальному углу')
    normal_vector_polar_angle = models.FloatField(default=0, verbose_name='Нормаль к полярному углу')
    point = models.ForeignKey(Point, on_delete=models.CASCADE)
    surface = GenericRelation(Surface)


class Result(models.Model):
    RESULT_TYPE_CHOICES = (
        (0, 'Изображение'),
        (1, 'Численные значения'),
        (2, 'Изображение и численные значения'),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_dt = models.DateTimeField(auto_now_add=True)
    black_hole = models.ForeignKey(BlackHole, on_delete=models.CASCADE)
    observer = models.ForeignKey(Observer, on_delete=models.CASCADE)
    surface = models.ForeignKey(Surface, on_delete=models.CASCADE)
    resolution = models.SmallIntegerField(default=256, verbose_name='Разрешение')
    accuracy = models.FloatField(default=1e-8, verbose_name='Точность')
    result_type = models.PositiveSmallIntegerField(default=2, choices=RESULT_TYPE_CHOICES, verbose_name='Тип результата')
    return_code = models.PositiveSmallIntegerField(default=0, editable=False)
    usr_email = models.CharField(blank=True, max_length=200, verbose_name='Почта')
    viewed = models.BooleanField(default=False, editable=False)


    def __str__(self):
        return str(self.id)


@receiver(pre_save, sender=Surface)
def set_package_closed(sender, instance, **kwargs):
    cr_surface = instance.surface_object
    if cr_surface is None:
        raise ValidationError('NO SUCH OBJECT')

cosmo_web/bh_compute/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader

# Create your views here.


def index(request):
    context = {}
    template = loader.get_template('bh_compute/index.html')
    return HttpResponse(template.render(context, request))


def about(request):
    context = {}
    template = loader.get_template('bh_compute/about.html')
    return HttpResponse(template.render(context, request))

cosmo_web/templates/base_site.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}

  {% block head %}

  {% block meta %}
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% endblock meta %}
  <title>Silhouette | {% block title %}{% endblock title %}</title>
      {% block stylesheets %}
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'join/bootstrap4/css/bootstrap.min.css' %}">
    <link href="{% static 'custom/bh_compute/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'custom/bh_compute/css/main.css' %}" rel="stylesheet">
     {% endblock stylesheets %}
     {% endblock head %}
</head>
<body>
{% block body %}
<body id="top"><div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">Проект Силуэт</h3>
            {% block menu %}
	<nav class="nav nav-masthead">
        <ul class="nav-menu">
          <li><a href="{% url 'bh_compute:index' %}">Главная</a></li>
          <li><a href="{% url 'bh_compute:about' %}">О проекте</a></li>
          <li><a href="#">Рассчитать</a></li>
        </ul>
      </nav>
            {% endblock menu %}
        </div>
      </div><br>
         {% block content %}
        {% endblock content %}
         {% block footer %}
      <div class="mastfoot">
        <div class="inner">
          <p>&copy; Silhouette. Designed by Dmitry Potapov</p>
        </div>
      </div>
          {% endblock footer %}
        {% block javascripts %}
    <script type="text/javascript" src="{% static 'join/jquery-3.3.1.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'join/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'join/bootstrap4/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'custom/bh_compute/js/mn_scr.js' %}"></script>
        {% endblock javascripts %}
    {% endblock body %}
  </body>
</html>

cosmo_web/templates/bh_compute/about.html
{% extends "base_site.html" %}
{% load static %}

{% block title %}О проекте{% endblock title %}
{% block content %}
        <div class="inner cover">
        <h1 class="cover-heading">О проекте</h1>
        <p class="lead cover-copy">Данный проект развивался при поддержке ФИАН.</p>
      </div>
        {% endblock content %}

cosmo_web/templates/bh_compute/index.html
{% extends "base_site.html" %}
{% load static %}

{% block title %}Главная{% endblock title %}
{% block content %}
        <div class="inner cover">
        <h1 class="cover-heading">Тени чёрных дыр</h1>
        <p class="lead cover-copy">Воспользуйтесь уникальной возможностью произвести математические рассчеты и увидеть силуэт чёрных дыр.</p>
        <p class="lead"><a href="#" role="button" class="btn btn-lg btn-default btn-notify">Рассчитать</a></p>
      </div>
        {% endblock content %}